### ISSUE TITLE
Zacian listed as Uber

### ISSUE THREAD

**Issue by TeamEnlighten** [Zarel/Pokemon-Showdown-Dex#17]
Zacian tier entry reading as Uber, although in PS is now rated AG. Are tiers updated manually when using the Pokemon Showdown NPM? Thank you!

**Comment by Zarel** [comment]
![image](https://user-images.githubusercontent.com/551184/140007231-4bff6a5a-1a5b-4057-9c8b-f3b34ec1d7ab.png)

Looks like AG to me...

The Dex should be updated automatically for these sorts of things.

**Comment by TeamEnlighten** [comment]
![Screenshot 2021-11-02 215322](https://user-images.githubusercontent.com/87457810/140011737-abf47454-6863-4e8a-97ad-2c808eea1a52.png)
![Screenshot 2021-11-02 215651](https://user-images.githubusercontent.com/87457810/140011739-43f9eadf-0f0b-4a10-b590-f567ff371fcd.png)

Please see screenshots. It is coming up as an Uber from the NPM version 0.11.7

**Comment by TeamEnlighten** [comment]
Sorry Zarel, just realized that although this is the dex repository, it is not the pokemon showdown repository. I have submitted the issue to Smogen. Thank you for your time!
