### ISSUE TITLE
Dex freezes when selecting an egg-move

### ISSUE THREAD

**Issue by Rockpick** [Zarel/Pokemon-Showdown-Dex#19]
Hey this Pokedex is the best one out there. Very fast, good overview!

I noticed that (for quite some time now), when you select an egg move from a Pokémon's move pool, the dex just freezes. 
To replicate, just search "Charizard" and select "Belly Drum" from it's egg moves. Nothing happens. When you then select any other move, nothing happens either. Reloading gets the Dex working again.

Cheers, and thanks for this awesome Dex

**Comment by joebangara43903** [comment]
![image](https://user-images.githubusercontent.com/131228993/232964797-806af775-fe5f-4b17-95ce-e3b654951c7b.png)

**Comment by Zarel** [comment]
Looks like it's fixed now. I'm guessing it was probably one of the gen updates. Sorry about that!
